name: Monitor Homebrew Formula

on: workflow_dispatch

env:
  file_changed: ${{ false }}

jobs:
  check-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v4

    - name: Fetch released version of Chapel formula
      run: |
        curl -o hb_master_chapel.rb https://raw.githubusercontent.com/homebrew/homebrew-core/master/Formula/c/chapel.rb
    - name: Compare the released version with the chapel-release.rb
      id: compare
      run: |
        if ! cmp -s hb_master_chapel.rb util/packaging/homebrew/chapel-release.rb; then
          echo "file_changed=true" >> $GITHUB_ENV          
        else
          echo "file_changed=false" >> $GITHUB_ENV
        fi
    - name: Create a new branch if file has changed      
      if: ${{ env.file_changed == 'true' }}      
      run: |
        git config --global user.email "github-action-bot@email.com"
        git config --global user.name "github action"
        git checkout -b update-chapel-homebrew-release
        mv hb_master_chapel.rb util/packaging/homebrew/chapel-release.rb
        git add util/packaging/homebrew/chapel-release.rb
        git commit -m "Update chapel-main.rb with changes from chapel.rb"
        git push --set-upstream origin update-chapel-homebrew-release
        echo "Homebrew has updated the formula!"        
    - name: create pull request
      run: gh pr create -B main -H update-chapel-homebrew-release --title 'Update our copy of the released Homebrew formula' --body 'Created by Github action'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

